export const GETNEWSLIST_START = "GETNEWSLIST_START";
export const GETNEWSLIST_SUCCESS = "GETNEWSLIST_SUCCESS";
export const GETNEWSLIST_FAILED = "GETNEWSLIST_FAILED";
export const GETNEWSLIST_PROCESS = 'GETNEWSLIST_PROCESS';
export const GETNEWSITEM_SUCCESS = 'GETNEWSITEM_SUCCESS';
export const GETNEWSITEM_FAILED = 'GETNEWSITEM_FAILED';